apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: ashapp
spec:
  selector:
    app: history-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

