apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ashapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ashwanth01/ashapp-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: SPRING_BOOT_URL
          value: "http://history-service:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ashapp
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

