apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service
  namespace: ashapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
      - name: history-service
        image: ashwanth01/history-service:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: ashapp
spec:
  type: ClusterIP
  selector:
    app: history-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

