apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: ashapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: ashwanth01/ashapp-login:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: ashapp
spec:
  type: ClusterIP
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

